package com.qzh.daka.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qzh.daka.entity.DailyHealthDetails;
import com.qzh.daka.entity.LogUser;

import com.qzh.daka.greendao.DailyHealthDetailsDao;
import com.qzh.daka.greendao.LogUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dailyHealthDetailsDaoConfig;
    private final DaoConfig logUserDaoConfig;

    private final DailyHealthDetailsDao dailyHealthDetailsDao;
    private final LogUserDao logUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dailyHealthDetailsDaoConfig = daoConfigMap.get(DailyHealthDetailsDao.class).clone();
        dailyHealthDetailsDaoConfig.initIdentityScope(type);

        logUserDaoConfig = daoConfigMap.get(LogUserDao.class).clone();
        logUserDaoConfig.initIdentityScope(type);

        dailyHealthDetailsDao = new DailyHealthDetailsDao(dailyHealthDetailsDaoConfig, this);
        logUserDao = new LogUserDao(logUserDaoConfig, this);

        registerDao(DailyHealthDetails.class, dailyHealthDetailsDao);
        registerDao(LogUser.class, logUserDao);
    }
    
    public void clear() {
        dailyHealthDetailsDaoConfig.clearIdentityScope();
        logUserDaoConfig.clearIdentityScope();
    }

    public DailyHealthDetailsDao getDailyHealthDetailsDao() {
        return dailyHealthDetailsDao;
    }

    public LogUserDao getLogUserDao() {
        return logUserDao;
    }

}
